apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: pv-pvc-sc-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: ebs-vol
          mountPath: /mnt/ebs/
      volumes:
      - name: ebs-vol
        persistentVolumeClaim:
          claimName: ebs-pvc
